// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAreas() {
  return window['go']['main']['App']['GetAreas']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ReloadData() {
  return window['go']['main']['App']['ReloadData']();
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function UpdateChannel(arg1) {
  return window['go']['main']['App']['UpdateChannel'](arg1);
}

export function UpdateDataChannel(arg1) {
  return window['go']['main']['App']['UpdateDataChannel'](arg1);
}

export function UpdateReceiver(arg1) {
  return window['go']['main']['App']['UpdateReceiver'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}

export function UpdateTransmitter(arg1) {
  return window['go']['main']['App']['UpdateTransmitter'](arg1);
}

export function UpdateTransponder(arg1) {
  return window['go']['main']['App']['UpdateTransponder'](arg1);
}
