// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function SelectFile():Promise<main.Container>;

export function UpdateReceiver(arg1:main.Receiver):Promise<main.Container>;
