// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetAreas():Promise<main.Areas>;

export function GetSettings():Promise<main.Settings>;

export function ReloadData():Promise<main.Container>;

export function SelectFile():Promise<main.Container>;

export function UpdateChannel(arg1:main.Channel):Promise<main.Container>;

export function UpdateDataChannel(arg1:main.UpdateDataChannel):Promise<main.Container>;

export function UpdateReceiver(arg1:main.Receiver):Promise<main.Container>;

export function UpdateSettings(arg1:main.Settings):Promise<main.Settings>;

export function UpdateTransmitter(arg1:main.Transmitter):Promise<main.Container>;

export function UpdateTransponder(arg1:main.Transponder):Promise<main.Container>;
